volumes:
  el_data:
  cl_data:
services:
  reth:
    build:
      context: .
      dockerfile: reth.dockerfile
    ports:
      - "8545:8545"
      - "8551:8551"
      - "6060:6060"
    volumes:
      - "el_data:/db"
  lighthouse:
    build:
      context: .
      dockerfile: lighthouse.dockerfile
    ports:
      - "5052:5052"
    volumes:
      - "cl_data:/db"
    depends_on:
      - reth
