# Define volumes for the containers to persist data to
volumes:
  el_data:
  cl_data:

# Use the shared network across all stacks
networks:
  anton-net:
    external: true

services:
  reth:
    build:
      context: .
      dockerfile: reth.dockerfile
    ports:
      - "8545:8545"
      - "8551:8551"
      - "6060:6060"
    volumes:
      - "el_data:/db"
    networks:
      - anton-net
  lighthouse:
    build:
      context: .
      dockerfile: lighthouse.dockerfile
    ports:
      - "5052:5052"
    volumes:
      - "cl_data:/db"
    networks:
      - anton-net
    depends_on:
      - reth
